name: berlin_service_portal
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_flavor: ^3.1.3
  openid_client: ^0.4.8
  url_launcher: ^6.3.1
  dio: ^5.7.0
  stomp_dart_client: ^2.1.0
  scrollview_observer: ^1.24.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  flutter_map_cancellable_tile_provider: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/